admin_start = '<b>Добро пожаловать, хозяйка</b>'
components_text = '<b>Выберите действие</b>'
select_group_text = '<b>Выберите группу</b>'
select_name_text = '<b>Выберите название</b>'
select_price_text = '<b>Введите цену</b>'
group_components_text = '<b>Выберите компонент</b>'
view_component_text = lambda component: (f'<b>Компонент: {component.name}\n'
                                         f'Цена: {component.price}\n'
                                         f'Группа: {component.group}\n'
                                         f'Активен: {'✅Да' if not component.hide else '❌Нет'}</b>')
edit_component_name_text = '<b>Введите новое название</b>'
edit_component_price_text = '<b>Введите новую цену</b>'
create_text = lambda component: ('<b>Компонент успешно создан\n'
                                 'Добавьте ещё или откройте меню снизу</b>')
new_reserve_text = lambda data: f'<b>Новый заказ!</b>'
main_entries_text = '<b>Выберите заказ</b>'
main_not_entries_text = '<b>Сейчас заказов нет</b>'
admin_view_entry_text = lambda entry, component_dict: (f'<b>Заказ id: {entry.id}\n\n'
                                                       f'Описание: {entry.description}\n'
                                                       f'Создан: {entry.create_at.strftime("%d.%m.%Y %H:%M")}\n'
                                                       f'client_id: {entry.client_id}\n'
                                                       f'контакт: {entry.contact}\n'
                                                       f'Компоненты заказа: \n'
                                                       f'{''.join([f'{key} - {value}\n' for key, value in component_dict.items()])}</b>')
admin_completed_entries_text = '<b>Выберите заказ</b>'
admin_not_completed_entries_text = '<b>Сейчас нет завершенных заказов</b>'
admin_view_completed_entry_text = lambda entry, component_dict: (f'<b>Заказ id: {entry.id}\n\n'
                                                 f'Описание: {entry.description}\n'
                                                 f'Создан: {entry.create_at.strftime("%d.%m.%Y %H:%M")}\n'
                                                 f'Завершен: {entry.completed_at.strftime("%d.%m.%Y %H:%M")}\n'
                                                 f'client_id: {entry.client_id}\n'
                                                 f'контакт: {entry.contact}\n'
                                                 f'Компоненты заказа: \n'
                                                     f'{''.join([f'{key} - {value}\n' for key, value in component_dict.items()])}</b>')
admin_delete_entry_text = lambda entry: f'<b>Заказ id: {entry.id} удален</b>'
admin_complete_entry_text = '<b>Заказ выполнен</b>'